services:
  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_estudos
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports:
      - 5000:80
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123!'
    depends_on:
      - db
